### ISSUE TITLE
Require Secure if SameSite=None

### ISSUE THREAD

**Issue by inexorabletash** [WICG/cookie-store#104]
Per https://tools.ietf.org/html/draft-west-cookie-incrementalism-00

This would manifest in the "set a cookie" steps as a check/failure.

Wording depends on the outcome of https://github.com/WICG/cookie-store/issues/102

cc: @chlily1 @oyiptong @pwnall

**Comment by ayuishii** [comment]
Thanks for this issue @inexorabletash 

I agree, this requirement to be “secure” during cross-site seems a positive change to move towards usages of more secure cookies. 

Created an implementation issue for Chromium [here](https://crbug.com/1066142). Although the implementation details may change depending on the outcome of this [issue](https://github.com/WICG/cookie-store/issues/121) on removing the `secure` option and not allowing non-secure. If so, I will update this issue, and the implementation ticket accordingly.
