### ISSUE TITLE
Intent to migrate cookie-store to WebApps WG

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/cookie-store#105]
Hi Folks working on this... with the Web Apps WG now up and running, we are ready to adopt this specification into the WG for formal standardization along the w3c rec track. 🎉 

Before doing so, I could use a bit of help just filling out the template below... I've got things started already, but those with knowledge of the spec please jump in. 

## Intent to Migrate: cookie-store

Use this as a template to include as an issue in your specification's repository. That issue can be closed after migration, but keep it as part of the public record.

### Working group decision to adopt
[Web Apps WG Charter](https://www.w3.org/2019/05/webapps-charter.html#wicgspecs)

### Proposal

* [The explainer](explainer.md) is a developer-oriented preview of the API.
* [The specification draft](https://wicg.github.io/cookie-store/) is aimed at browser developers.

### Summary
An asynchronous Javascript cookies API for documents and workers. This reduces jank, gives service workers access to cookies, and brings a bunch of other cross-browser and developer benefits (described in more detail in the [explainer](https://github.com/WICG/cookie-store/blob/master/explainer.md)).  

### Motivation and Use Cases
Motivation and use cases are described in the [explainer](https://github.com/WICG/cookie-store/blob/master/explainer.md). 

### Compatibility Risk

Please characterize how much we might regret standardizing this new feature were we to change or remove it in the future. 

### Ongoing technical constraints

What technical constraints will be added to user agents implementing this feature?

Will this feature be supported in all environments (desktop, mobile, tablets, TV, eBooks, automotive, etc.)?

Yes or no. If no, explain why certain user agents will not be included in your implementation.

### Link to implementation experience and demos
If your proposal has implementation experience or demos, please provide links, including common patterns in deployed libraries. Otherwise, indicate if there are none.

* [Blink intent-to-implement](https://groups.google.com/a/chromium.org/d/msg/blink-dev/gU-tSdjR4rA/hAYgmxiHCAAJ)

### Data
What data do you have available that indicates that this enhancement will affect many users of the Web. Quantify the fraction of websites that are currently using something similar to this feature. Or, if a new feature, characterize the reason that you expect this to be far reaching.

### Security and Privacy
Other than cookie access from service worker contexts, this API is not intended to expose any new capabilities to the web. 

The privacy issues with cookies are well-known. This specification does not attempt to address those privacy issues. 

More extensive discussion:
https://wicg.github.io/cookie-store/#security

The proposal does not aim to change the cookie security model, or how cookies are handled at the network layer.

### Accessibility
The API would integrate with existing browser UI to manage storage/cookies, but does not itself introduce any new UI, specially not in documents. 

### Internationalization
Does not affect internationalization.

**Comment by marcoscaceres** [comment]
@yoavweiss, unfortunately, seems the "Transfer Issue" thing is busted, so can't transfer this to the Admin repo.

**Comment by inexorabletash** [comment]
Is there implementation interest from anyone other than Chromium?

**Comment by cwilso** [comment]
(I.e., what's the motivation to pick this up in web-apps?)

**Comment by marcoscaceres** [comment]
Mozilla has some feedback we've provided,  but we've done some implementation work on cookie store and feel it's worth going ahead with:
https://github.com/mozilla/standards-positions/issues/94

**Comment by marcoscaceres** [comment]
Spoke to soon. We (Mozilla) have shifted position and are now looking to “defer” on implementing this. Rationale at the end of: 

https://github.com/mozilla/standards-positions/issues/94

We could check if the Apple or Microsoft folks might be interested in implementing?

**Comment by annevk** [comment]
Let's dupe this into #186?

**Comment by inexorabletash** [comment]
This has the most structure but I guess #186 has the most recent comments? Closing.
