### ISSUE TITLE
Examples incorrectly use `event.waitFor` instead of `event.waitUntil`

### ISSUE THREAD

**Issue by Hexcles** [WICG/cookie-store#107]
Stumbled upon the explainer and noticed the example used `event.waitFor` in a service worker. A quick search shows a few other matches including in the spec text, too: https://github.com/WICG/cookie-store/search?q=waitfor&unscoped_q=waitfor

They should probably be `event.waitUntil` instead.

**Comment by ImUrX** [comment]
fixed by #109
