### ISSUE TITLE
Why do we have ExtendableCookieChangeEvent ?

### ISSUE THREAD

**Issue by inexorabletash** [WICG/cookie-store#117]
`ExtendableEvent` is for things like "install" in the SW lifecycle so that the lifecycle stage can be kept alive while async operations are performed.

There's no example or reason given for using this type of event in the SW variant. Can we collapse the event types?

**Comment by mkruisselbrink** [comment]
`ExtendableEvent` is for all events in the SW so the SW itself can be kept alive while the async operations are performed. It has nothing to do with lifecycle bits specifically. I.e. we also have ExtendableMessageEvent etc.

**Comment by inexorabletash** [comment]
Ah, thanks. I'll add a non-normative note to the spec

**Comment by inexorabletash** [comment]
Added to PR 521478b488852a68bd5da3b8d5588bfdaa5fa20d
