### ISSUE TITLE
Call out what's in the various Chrome Origin Trials

### ISSUE THREAD

**Issue by inexorabletash** [WICG/cookie-store#122]
In Chrome we're planning to have two Origin Trials, one for the Window side of the API and one for the Service Worker side. Folks reading the explainer may not be following closely, so we should call out which chunks of the API (examples, IDLs, etc) are in each.

Over in IndexedDB I call out this sort of thing using

> 🚧 The foo is available starting in bar. 🚧

So we may want to do that in the Explainer and Spec here.

**Comment by ayuishii** [comment]
Thanks @inexorabletash,
We ended deciding to combine the two OTs for M84. It will happen all at once. 
Is the explainer still a good place to put this info? Or do you think it won't be necessary if its available all at once.

**Comment by inexorabletash** [comment]
Since it's going out all at once, I don't think we need this.
