### ISSUE TITLE
Is `matchType` necessary?

### ISSUE THREAD

**Issue by mikewest** [WICG/cookie-store#128]
The explainer presents the Google+ API as a use case for the `matchType: 'starts-with'` option. It's not clear to me that that's something we can reasonably point to today. If we dropped it from `CookieStoreGetOptions`, we could simplify the `Window` exposure by dropping the `CookieStoreGetOptions` variants of `get()` and `getAll()` (as `url` is only meaningful in Service Workers).

**Comment by ayuishii** [comment]
Thanks for the feedback @mikewest !
I think this would be a good candidate for getting feedback and observing how this is used during Origin Trial. I can put in place some metrics to do so. Does this sound ok?

**Comment by domenic** [comment]
Where did the origin trial feedback end up in this regard?

**Comment by ayuishii** [comment]
Looking through our metrics and connecting with our partner, looks like we don't have a strong case to keep `matchType`. 
I've created a [bug](https://github.com/WICG/cookie-store/issues/128) to track removal and will update the spec / explainer on this change.
