### ISSUE TITLE
Editorial nit: you can use options["foo"] for dictionary members

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#155]
I.e. instead of

```html
|options|' {{CookieStoreDeleteOptions/name}} dictionary member
```

you can do

```html
|options|["{{CookieStoreDeleteOptions/name}}"]
```

Both are fine, but the latter is a bit more pleasant to read.

I only mention this because @inexorabletash seems to find making these sorts of changes relaxing :)

**Comment by inexorabletash** [comment]
Hah. Don't wait on me to make the change tho.
