### ISSUE TITLE
Why use [Replaceable]?

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#157]
[Replaceable] is generally used to work around legacy compat problems. Did that occur for `window.cookieStore`? If so, noting that in the document might be a good idea. If not, then I'd suggest removing it.

It certainly doesn't seem necessary for `ServiceWorkerGlobalScope`.

**Comment by ayuishii** [comment]
Thanks for pointing this out!
@pwnall Do you have more context around this?

**Comment by inexorabletash** [comment]
This was almost certainly cargo-culted, but I'm not sure from where.

**Comment by pwnall** [comment]
I think I cargo-culted `[Replaceable]` from somewhere. I think it makes some getters / setters appear, and I must have concluded that we need this to support polyfilling cookieStore, in case that need ever arises.

**Comment by pwnall** [comment]
@domenic as far as I'm concerned, you're an authority on WebIDL. If you think we don't need this, happy to remove.

**Comment by domenic** [comment]
Sounds good; let's get rid of it :)

**Comment by ayuishii** [comment]
Updated spec and will continue to track Chrome implementation [here](https://crbug.com/1124891)
