### ISSUE TITLE
Task queuing needs a task source (and document)

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#159]
> Queue a task to fire a change event named "change" with changes at window’s CookieStore on window’s responsible event loop.

This should use [queue a global task](https://html.spec.whatwg.org/multipage/webappapis.html#queue-a-global-task) given _window_, to pass along the document when appropriate. But that's pretty minor (and easy for the reader to infer).

The trickier question is what task source to use for the queued task. I'm curious which one Chromium uses? If it's kMiscPlatformAPI, then that's bad and we need to pick a new one.

**Comment by inexorabletash** [comment]
It's `kMiscPlatformAPI` - how about `kDOMManipulation` like BroadcastChannel and Local/SessionStorage ?

**Comment by ayuishii** [comment]
Updated spec to use `kDOMManipulation`. Will track implementation [here](https://crbug.com/1128057).
