### ISSUE TITLE
draft-ietf-httpbis-rfc6265bis links are outdated

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#165]
All the links go to https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03, but the latest version is https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-06 (6 instead of 3).

It looks like https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis will always redirect to the latest version, so probably the right thing to do is replace all instances of the -03 URL with the unversioned URL.

**Comment by ayuishii** [comment]
Thanks for finding this!
Addressed in https://github.com/WICG/cookie-store/pull/166
