### ISSUE TITLE
Algorithms for CookieStoreManager treat |this| as a service worker registration

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/cookie-store#180]
The algorithms for the methods on CookieStoreManager in https://wicg.github.io/cookie-store/#CookieStoreManager all use `Let registration be this.`, and then operate on `registration`as if it is a `service worker registration`. But `this` in this context would be the actual `CookieStoreManager` object.

The `CookieStoreManager` object probably needs to have an associated service worker registration, which the algorithms can then use instead.

**Comment by ayuishii** [comment]
Thanks for the guidance!
Issue addressed here: https://github.com/WICG/cookie-store/pull/181
