### ISSUE TITLE
How to install this 

### ISSUE THREAD

**Issue by Stevemoretz** [WICG/cookie-store#187]
I want to use it on service worker for setting and getting a value would you please tell me how to install, and show me an example?

**Comment by inexorabletash** [comment]
There's nothing to install - this API will appear soon in [Chrome 87](https://www.chromestatus.com/feature/5658847691669504) (and presumably other Chromium-based browsers).

The [introduction to the spec](https://wicg.github.io/cookie-store/#intro) has examples on [setting](https://wicg.github.io/cookie-store/#intro-modify) and [getting](https://wicg.github.io/cookie-store/#intro-query) values.

**Comment by Stevemoretz** [comment]
Oh so it's really new, I was looking for something backward compatible, what would you suggest it's stupid that right now I send the push information from service worker to server on every page load.I want to send it only when push information changes but I have no idea how to save data whitin a service worker

**Comment by inexorabletash** [comment]
[Indexed DB](https://w3c.github.io/IndexedDB/) and [Cache Storage](https://w3c.github.io/ServiceWorker/#cache-objects) are more appropriate for local storage and are available in both Window and Service Worker contexts.
