### ISSUE TITLE
Fix up encoding definitions/references

### ISSUE THREAD

**Issue by inexorabletash** [WICG/cookie-store#202]
Following dd2ddc7ce8b081ef10d913fc71b862059d8c1a4f there's this text:

> To encode a string, run UTF-8 encode on string.

This text is unnecessary, as places that need to encode invoke "UTF-8 encode" directly. We should either:

* Remove that line; or
* Define **encode** and then simplify the call sites from _"result of UTF-8 encoding var"_ to _"result of encoding var"_

At the same time, we should consider if this definition is worthwhile:

> To **decode** a value, run UTF-8 decode without BOM on value.

In theory we could remove that and make the UTF-8 decoding inline, but the "without BOM" part makes it wordier. 

cc: @recvfrom

**Comment by domenic** [comment]
Chiming in from the sidelines, I think using the wordier definitions and removing your own spec's definitions of "encode" and "decode" would make things clearer for the reader.
