### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [WICG/cookie-store#205]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See heycam/webidl#2 for discussion.

**Comment by inexorabletash** [comment]
I think that's fine. This may require updating these definitions a bit:

https://wicg.github.io/cookie-store/#dom-cookieinit-expires - change the type
https://wicg.github.io/cookie-store/#dom-cookielistitem-expires - change the type
https://wicg.github.io/cookie-store/#as-a-timestamp - fine as is?
https://wicg.github.io/cookie-store/#date-serialize - just change the type name?
https://wicg.github.io/cookie-store/#delete-a-cookie - talks about "earliest representable date" ... probably still okay

**Comment by domenic** [comment]
Oh jeez, my bad for merging early then. /Cc @dontcallmedom

It seems like cookies might actually need EpochTimeStamp instead of DOMHighResTimeStamp since they need to be compatible with JS Date.

**Comment by ayuishii** [comment]
https://github.com/WICG/cookie-store/pull/208 looks like its updated the spec to use EpochTimeStamp.
@inexorabletash is there anything left for this issue?

**Comment by inexorabletash** [comment]
https://www.w3.org/TR/hr-time-3/#dom-epochtimestamp says EpochTimeStamp is just a rename of DOMTimeStamp; we still need to update the spec to `DOMHighResTimeStamp`

I can put up a PR for that.

**Comment by ayuishii** [comment]
SG, thanks for the PRs. Filed a crbug for chromium.
https://crbug.com/1416988
