### ISSUE TITLE
"path is not null" but path is not nullable

### ISSUE THREAD

**Issue by annevk** [WICG/cookie-store#227]
I don't see how https://wicg.github.io/cookie-store/#set-a-cookie makes sense. Path is not nullable in the current API.

**Comment by annevk** [comment]
In the work @johannhof and I are doing on Cookie Layering we are going to assume that Cookie Store always create a cookie with a path so that when it hands off the cookie to be stored its path is accurate.

**Comment by ayuishii** [comment]
Thanks for the catch! This should now be resolved with the PR above.
