### ISSUE TITLE
A few observations on existing cookie APIs

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [WICG/cookie-store#35]
This is a follow-up of https://github.com/WICG/async-cookies-api/issues/31#issuecomment-239707182. I am just opening a new issue so that we don't keep the discussion in an unrelated one.

This is a response for @bsittler observations.

> I'm glad to see this isn't the only API that tries to change the default path for Set-Cookie 😄

This has come after much push back from js-cookie team. We just conceded because it was proven with many reports over the years that the default path rules violate the Principle of Least Astonishment for developers that work with cookies.

jQuery cookie didn't changed the `Path` until the version 2.0. See [this](https://github.com/js-cookie/js-cookie/issues/25) issue for some reported links and context on why that decision was made. 

Answering to @bsittler questions:

> Also, why synchronous? Is using await ... and/or .then(...) problematic for some reason?

Not at all, it is just that I thought it might make sense to have a synchronous API for compatibility purposes. Many implementations have a similar interface and they are pretty well established in the ecosystem:
- https://github.com/ScottHamper/Cookies
- https://github.com/florian/cookie.js

[This issue](https://github.com/js-cookie/js-cookie/issues/125) sums up very well why we should refrain from creating different APIs. In the last versions, js-cookie tried to be as similar as possible to the interface of other similar implementations to be more portable.

If there's a way to fix the problems that drove the creation of this proposal with a new cookie API that fixes a multitude of other problems (like the encoding issues), then I guess we could leverage this to do that too. Although I still need to understand in details what is the problem that drove the creation of this proposal.

I don't think that being asynchronous by default even when asynchronicity is not necessary would cause any harm other than unnecessary `.then`s everywhere, but that's just theoretical purity.

> Are there other event handlers that need to be blocked/prevented from firing until the cookie operation completes?

Even handlers from which kind? AFAIK there's no event handler in the synchronous `document.cookie` API, it is just I/O. I probably didn't understand the question.

> Or is this primarily due to a desire to use it in the inner implementation of pre-existing APIs already exporting script-blocking APIs for cookie operations?

If we could build something that mimics the behavior of an API like js-cookie we could gradually make it cease to exist. There's enough evidence that the features it supports are useful in the wild.

Besides that, there's no need to implement asynchronicity for a synchronous API if there is another standard equivalent that fixes the same issues. The problem is that if the standard don't address things like encoding issues or allows encoding to be overridden for server-side compatibility (like js-cookie converters), then we would need to keep abstracting `document.cookie` and the new low-level asynchronous API in a library that complements with the features lacking in the standard.

It would be awesome if we could dedicate the effort to fix the `document.cookie` API. Would it make sense?

**Comment by bsittler** [comment]
Async removes the storage mutex from blocking the thread and also allows adding transactional features later if desired. See e.g. https://lists.w3.org/Archives/Public/public-whatwg-archive/2009Sep/0083.html

Async also allows browsers to put UI (e.g. permission prompts) between the calling function and access to the cookie capabilities without interrupting non-cookie-dependent parts of a page.

And finally the move out of "document" allows it to run in a service worker which has no "document", and which also cannot block event handling without negatively impacting web page/app performance due to being in the critical path for fetch interception.

**Comment by FagnerMartinsBrack** [comment]
> However, if this async cookies API proposal were to become clearly specified, widely implemented, and made available across most modern web browsers I believe it would become a viable alternative to document.cookie and would also reduce the difficulty of implementing cookie support cleanly in the script-driven parts of a web application.

Detaching the cookie API from `document.cookie` looks good in theory mostly for the last part "would also reduce the difficulty of implementing cookie support cleanly in the script-driven parts of a web application".

In this case, would the cookies still be sent on every HTTP request? If yes, since it would be async, wouldn't it make it easier for some race condition to happen when the developer sets a cookie to be sent on every HTTP request?

By the way, is there a list with a TL;DR of the problems that were discussed but nobody could reach a reasonable conclusion yet?

PS.: My main point of before was mostly about this API interface (`getAll()`, etc.) that goes against the way most cookie libraries interface are defined, not about the feasibility of async cookies. Since this is a sketch, does it mean that this API interface is not final and it could be possible to be changed in the future? I ask this because if we use the same interface as other cookie libraries and just add async capabilities (like `Cookies.get(key).then((value) =>)`), then it will be easier to slowly move from js-cookie, for example, to a standard spec.

**Comment by pwnall** [comment]
@FagnerMartinsBrack In case you're still interested, I've recently updated the explainer to reflect the current experimental shape of what we've implemented in Chrome.

Regarding raciness -- yes, it is quite possible to use this API in a racy way. https://github.com/WICG/cookie-store/blob/gh-pages/explainer.md#data-races cover a few examples. At the same time, note that you can get the same raciness from two `fetch` API calls, one of which invokes a server-side API that sets a cookie.

Regarding ability to change the API -- we plan to start an Origin Trial in Chrome soon, the point of which would be to get feedback from developers, and use it to improve the API. If you're interested, you can use the Experimental Web Platform Features flag today with Canary to try to build against this API. We'd welcome your feedback.

I'm going to close this issue, as it's fairly high level and doesn't seem to have anything specific to the concrete shape of the current API. If you have concrete feedback for the current API shape, please don't hesitate to open new issues.
