### ISSUE TITLE
Should include sameSite attribute in reading/monitoring APIs, at least inside ServiceWorker

### ISSUE THREAD

**Issue by bsittler** [WICG/cookie-store#38]
document.cookie reveals all cookies (sameSite or otherwise) but doesn't tell the script which ones have SameSite=lax or SameSite=strict. However, a ServiceWorker won't be able to know whether a cookie should be considered when handling a specific request unless it knows both:
- what SameSite category the cookie is in (if any; what this issue is about) and
- what SameSite category the intercepted fetch or foreign is in (needs a separate issue in ServiceWorker)
#36 covers the separate issue of exposing sameSite in the write interface, but both should probably use the same enum to represent the tristate

**Comment by pwnall** [comment]
Closing in favor of #36. The returned cookies will match the same-site attribute name and values used by the write API.
