### ISSUE TITLE
Observers should receive a consistent snapshot of the cookie store as part of each observed change

### ISSUE THREAD

**Issue by bsittler** [WICG/cookie-store#39]
Observers should always receive a consistent snapshot of the cookie store as part of each observed change so that they do not need to maintain their own backing and also so they do not need to worry about potential skew as a result of prematurely terminated event handlers.

**Comment by pwnall** [comment]
This seems fairly expensive -- for multi-process browsers, we'd have to choose between batching changes or sending snapshots across processes for every change event.

I think that guaranteeing that events will be received in some correct order is sufficient for observing to maintain a snapshot. The document / SW would use `cookieStore.getAll` when it starts up, then apply the diffs obtained from change events. If an event handler is terminated, the document / SW has been terminated as well, and can use a getAll next time it wakes up again.

I'll close this to mean we've thought of the issue. Should feedback from Chrome's origin trials indicate that we have a gap here, we can resume the discussion.
