### ISSUE TITLE
Rewrite example code for async await

### ISSUE THREAD

**Issue by paulirish** [WICG/cookie-store#42]
It's how i'd expect most users to consume it

Just an idea. :)

**Comment by bsittler** [comment]
Thanks for the suggestion @paulirish &mdash; though I'm not completely sure I understand. Do you mean all the examples should use the async/await syntax? Or perhaps that all the examples should include async/await syntax, whether or not they also include an equivalent snippet using Promise/then-able syntax?

Some of the example code does use "await" inside async functions, e.g. https://github.com/WICG/async-cookies-api/blob/gh-pages/cookies_test.js#L85 and (in the explainer) https://github.com/WICG/async-cookies-api/blob/gh-pages/explainer.md#reading (scroll down for the async/await version) - however based on earlier feedback I left some "classic" Promise-structured examples too to avoid confusing readers not yet familiar with the newer syntax

**Comment by bsittler** [comment]
(Also see discussion on https://github.com/WICG/async-cookies-api/pull/17 )

**Comment by pwnall** [comment]
@paulirish Thank you for the feedback!

I've updated the explainer with the latest changes we've done in Chrome. I think the examples use async / await wherever it makes sense to do so. If you spot places where that's not the case (and space would be saved), please point them out in specific issues / PRs.
