### ISSUE TITLE
Bikeshed: cookie store vs. cookie jar?

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#48]
Traditionally I've heard of the collection of cookies referred to as the cookie jar, not the cookie store.

Cookie store:

<img src="https://pbs.twimg.com/profile_images/505878286279270400/TpRnscX9.jpeg" alt="A cookie store in real life" width="300">

Cookie jar:

<img src="https://images-na.ssl-images-amazon.com/images/I/51xFK3b5-tL.jpg" alt="A cookie jar in real life" width="300">

**Comment by annevk** [comment]
In informal usage there's usually talk about the browser's cookie jar. So if you just want cookies for a site, maybe you need something else, e.g., a cookie platter.

**Comment by pwnall** [comment]
Sorry for the late response here.

Cookie jar seems to mean different things to different people -- I thought a cookie jar has all the cookies in the browser, and a request pulls some cookies out of the jar. I've also heard @bsittler's interpretation before.

The main reason I like `cookieStore` is (mentioned by @bsittler above) that it makes it fairly clear that you're using a storage API to talk to a database (store) somewhere. `cookieJar` seems too overloaded and opaque at the same time -- if we want something shorter than `cookieStore`, I'd suggest `cookies`.

@domenic @annevk It seems to me that the most productive way to figure this out is to have some sort of VC. How is this usually done?

**Comment by annevk** [comment]
@pwnall usually via a Doodle. I'm not sure we need one for naming though.

"Cookie jar" is out I think given the multiple interpretations. "Cookie store" is reasonable. "Cookies" will likely result in some compatibility issues.

Presumably the scope of these cookies is the host's registrable domain, except for cookies limited to HTTP? "Site cookies" works as it's accurate with regards to the scope and I don't think has any existing meaning.

**Comment by inexorabletash** [comment]
> How is this usually done?

The TAG is pretty good at bikeshedding names; they bring somewhat more diverse viewpoints and are usually already discussing things F2F. If we send this out for review we can specifically raise the name as an area for feedback.

**Comment by pwnall** [comment]
We didn't get any feedback on this name from the TAG review, so we'll stick with what we have (`cookieStore`).
