### ISSUE TITLE
Remove cookieStore.has

### ISSUE THREAD

**Issue by pwnall** [WICG/cookie-store#51]
The `has` method doesn't strike me as useful enough to warrant the extra weight in the spec, docs, and browser code. `get` resolves to null when `has` would return false, and I expect that most code that would use `has` can take advantage of the fact that null is falsey.

So, I'd like to remove the method from the WPT tests and from Chrome's implementation.

@domenic @inexorabletash Any thoughts?

**Comment by annevk** [comment]
Most other map-like things have this method, e.g., `Headers`, `URLSearchParams`, and `FormData`. It seems somewhat worth keeping therefore, as folks will expect it to be there and be surprised if their code doesn't work.

**Comment by inexorabletash** [comment]
I concur with @annevk (but am sympathetic to @domenic's concerns).

**Comment by pwnall** [comment]
Thank you very much for the feedback here!

I'm generally strongly in favor of consistency, as I have pretty bad memory. In this case, I'm having trouble seeing how the consistency plays out. While I recognize that the shorthand forms of `get` / `set` / `delete` look like map APIs, it troubles me that all the map-like APIs mentioned by @annevk are synchronous. If developers try to pretend that cookieStore is a map, they'll write racy code.

I think that @domenic's parallel with async-local-storage is quite useful! Here are the three main points I took from the discussion in https://github.com/domenic/async-local-storage/issues/3.

1) (fortunately, IMHO) Cookies don't store special JS values like `undefined`, and that `cookieStore.get` makes it easy to distinguish between a present value (resolves to a dictionary) and an absent value (resolves to `undefined`).

2) The opportunity for racy misuse applies here -- `if (await cookieStore.has(...)) { await cookieStore.get(...) }`

3) The deserialization cost isn't very relevant here. Unlike IDB values, cookies are small strings. In a multi-process browser, the dominating cost is IPC. In a browser that accesses the cookie database in the renderer process, the dominating cost is the database query.

So, `has` + `get` ends up being an anti-pattern, because it yields worse performance and has a window for raciness.

**Comment by inexorabletash** [comment]
In the interest of resolving this, I'm happy for us to remove `has()` and re-add it later.

**Comment by inexorabletash** [comment]
Pulled it from the spec for now since we yanked the tests/impl on the Chrome side. Can be added back easily.

**Comment by inexorabletash** [comment]
For the record: `CacheStorage` includes `has()` https://w3c.github.io/ServiceWorker/#cachestorage-interface
