### ISSUE TITLE
Where can I read the specification?

### ISSUE THREAD

**Issue by annevk** [WICG/cookie-store#52]
https://wicg.github.io/cookie-store/ doesn't have anything.

**Comment by inexorabletash** [comment]
cc: @rtoy - we need to either check in the .html or set up appropriate built magic...

**Comment by inexorabletash** [comment]
From offline conversation with @rtoy, it's still easiest to hand-build and check in the HTML, especially as we're not admins for the org.

**Comment by inexorabletash** [comment]
Fixed.

The spec is _very_ rough. Neither I nor @pwnall have done even a cursory pass over the whole thing, so it's probably not worth filing bugs against yet.
