### ISSUE TITLE
"startsWith" should be "starts-with"

### ISSUE THREAD

**Issue by pwnall** [WICG/cookie-store#54]
[W3C TAG's design principles](https://w3ctag.github.io/design-principles/#casing-rules) says that enumeration values should be lowecase, dash-delimited. The `matchType` dictionary member in `cookieStore.get` / `cookieStore.getAll` options takes the values `equals` and `startsWith`. According to the TAG principles, the latter should be `starts-with`.

**Comment by domenic** [comment]
Just came here to file this. This seems like a good thing to fix sooner rather than later if folks are going to be experimenting with this in a original trial or similar.

**Comment by pwnall** [comment]
Fixed in Chrome and explainer.

**Comment by inexorabletash** [comment]
And fixed in spec.
