### ISSUE TITLE
Include path and domain in get response

### ISSUE THREAD

**Issue by dfabulich** [WICG/cookie-store#55]
The spec and browsers allow multiple cookies with the same name to be set for different path/domain values. Occasionally, this happens by mistake, typically by forgetting to specify a path for a cookie, creating a painful experience for developers.

Worse, when this happens, it's impossible to delete (expire) these cookies on the client side, unless you can guess the path of the cookie to delete; there's no way to ask the browser to tell you the paths of duplicate cookies.

Here's an example of the (rather common) bug. If this code runs in a subdirectory path, it will set two cookies, each of which must be independently deleted by specifying the correct path.

```js
document.cookie = "cookie=root;path=/";
document.cookie = "cookie=unspecified";
console.log(document.cookie); // cookie=unspecified; cookie=root
document.cookie = "cookie=deleted;max-age=0";
console.log(document.cookie); // cookie=root
```

Currently, the CookieListItem definition includes the cookie's name and value, but it would be very helpful to include the path and domain, as well. This way, when multiple cookies with the same name are returned, you can inspect the cookie and tell the difference.

**Comment by dfabulich** [comment]
The WebExtension cookie API returns a whole bunch of other stuff in its `Cookie` object. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/Cookie

**Comment by dfabulich** [comment]
Hrm, the explainer says this is already available. https://github.com/WICG/cookie-store/blob/gh-pages/explainer.md#access-all-the-cookie-data but the spec only includes name and value. https://wicg.github.io/cookie-store/#CookieListItem

**Comment by inexorabletash** [comment]
Yeah, spec is _extremely_ rough and is mostly a placeholder based on the explainer plus old IDL. Needs updating. The plan is to include those.
