### ISSUE TITLE
delete: "equivalent" code isn't equivalent

### ISSUE THREAD

**Issue by dfabulich** [WICG/cookie-store#56]
The spec says that `await cookieStore.delete('__Host-COOKIENAME')` is equivalent to a longer sample that expires the cookie:

```js
let theVeryRecentPast = Date.now();
let expiredCookieSentinelValue = 'EXPIRED';
await cookieStore.set('__Secure-COOKIENAME', expiredCookieSentinelValue, {
  path: '/cgi-bin/',
  expires: theVeryRecentPast,
  secure: true,
  domain: 'example.org'
});
```

That doesn't look right to me. If anything it would be equivalent to this code which leaves the path and domain implicit:

```js
let theVeryRecentPast = Date.now();
let expiredCookieSentinelValue = 'EXPIRED';
await cookieStore.set('__Secure-COOKIENAME', expiredCookieSentinelValue, {
  expires: theVeryRecentPast,
});
```

**Comment by dfabulich** [comment]
Also, I generally recommend against using `Date.now()` as an expiry date. Use 1970 "Thu, 01 Jan 1970 00:00:01 GMT" instead.

Even better: use max-age 0. https://github.com/WICG/cookie-store/issues/57

**Comment by inexorabletash** [comment]
Agreed that `Date.now()` risks being racy (clocks are hard). Just `0` should be fine (i.e. Unix epoch as you suggest)

I believe we are not supporting strings for `expires` values to avoid exposing funky date parsing in yet another place in the platform.
