### ISSUE TITLE
Offer a deleteAll method

### ISSUE THREAD

**Issue by dfabulich** [WICG/cookie-store#58]
It would be helpful and convenient to provide a way to delete cookies in bulk, especially if it allowed `matchType: 'startsWith'`. Otherwise, developers would have to `getAll` the cookies and delete them individually.

```js
cookieStore.getAll().then(cookies => Promise.all(cookies.map(cookie => cookieStore.delete(cookie))));
```

**Comment by dfabulich** [comment]
Deleting all script-visible cookies is surprisingly complicated; so a one-line fix would be great. https://stackoverflow.com/questions/179355/clearing-all-cookies-with-javascript

**Comment by inexorabletash** [comment]
I was thinking about this as well from a test perspective; great to hear it's a common pain point for developers we could address.

Are there any additional nuances beyond supporting `matchType` ?

**Comment by dfabulich** [comment]
I suppose the main "nuance" is that some folks would incorrectly assume that `deleteAll` can delete cookies that aren't script-visible. (Some developers have wished for a JS API equivalent to the browser's "clear site data" feature; this would not do that.)

And perhaps it could be argued that it's better/clearer to force the user to `getAll` and then `delete` the results, to make it clearer that you can only `delete` the cookies you can `get`. (If so, it ought to be very easy to delete a bunch of CookieListItems, per issue #60.)

**Comment by dfabulich** [comment]
@pwnall mentioned [a nuance](https://github.com/WICG/cookie-store/issues/61#issuecomment-400113612) in issue #61: atomicity.

> having any form of multiple writes in the API means we'd have to consider atomicity guarantees. If we offered atomicity guarantees, that'd require new backend capabilities, at least in Chrome. If we didn't offer atomicity guarantees, this would be a very rough edge in the API.
> 
> On the benefits side, I'm guessing we'd get better latency by being able to batch multiple delete requests in a single IPC. I currently don't think this benefit outweighs all the extra complexity I've described above. However, I'm willing to reconsider if given a strong use case. If anyone here has that use case, please comment below, and I'll reopen the issue.

I think `deleteAll` would count as "any form of multiple writes."

I think `deleteAll` _might_ be a "strong enough" use case to warrant an atomicity guarantee. https://stackoverflow.com/questions/179355/clearing-all-cookies-with-javascript has been viewed hundreds of thousands of times and has hundreds of upvotes.

**Comment by pwnall** [comment]
Sorry for being unclear. To me, `deleteAll` is an API feature request, not a use case. A use case is a Web application that tries to accomplish a specific task under specific circumstances.

I think this is similar to #61 in terms of additional complexity vs performance. `deleteAll` would require special support from the cookie store backend, and we'd have to reason about atomicity. The example in the issue description strikes me as a great example of JS library / helper. The only benefit I see with implementing it in the browser is getting a (slight) performance improvement, so the use case would have to be really strong here.
