### ISSUE TITLE
Reference WebExtension Cookies API in Related Work

### ISSUE THREAD

**Issue by dfabulich** [WICG/cookie-store#59]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies
https://www.chromium.org/developers/design-documents/extensions/proposed-changes/apis-under-development/proposal-chrome-extensions-cookies-api

It's not clear whether the spec authors reviewed these APIs. It would be productive to get feedback from extension developers who have used these APIs, to see if they have any feedback. (It's very close to the proposed spec.)

**Comment by inexorabletash** [comment]
Good point, that was an oversight! The extensions API was definitely an inspiration to the design. I'm unsure if feedback was explicitly solicited, though.
