### ISSUE TITLE
Allow delete to accept an array

### ISSUE THREAD

**Issue by dfabulich** [WICG/cookie-store#61]
```js
cookieStore.getAll().then(
  cookies => Promise.all(
    cookies.filter(cookie => cookie.name.length > 6)
    .map(cookie => cookieStore.delete(cookie))
  )
);
```

Deleting a list of cookies is a mouthful, requiring `Promise.all` and a `map`. It would be nice if delete would accept an array.

```js
cookieStore.getAll().then(
  cookies => cookieStore.delete(
    cookies.filter(cookie => cookie.name.length > 6)
  )
);
```

**Comment by domenic** [comment]
-1; this kind of sugar is not something to build into the base primitive. All other promise-accepting APIs have this "problem", and the canonical solution is indeed to use Promise.all. We shouldn't come up with a one-off solution for cookie store.

**Comment by dfabulich** [comment]
(I assume by "promise-accepting APIs" you mean APIs that _return_ promises. I don't think any part of the cookie store API accepts/receives a promise as a parameter.)

Is there a written guideline (or even just a blog post) somewhere on why/where sugar should be avoided? (I'm sure this must be a frequently asked question.)

**Comment by domenic** [comment]
(Yeah, sorry, misspoke.)

I'm not aware of such a guideline in general. It's more just the general software engineering principle that you should solve the problem at the same level of generality that it occurs. If you find using Promise.all too verbose for performing multiple promise operations, then the proper way to solve that is at the language level, not for specific APIs.

**Comment by inexorabletash** [comment]
I think the Promise stuff in the OP's example is confusing things. So far as I can tell, the suggestion is for this:

```js
await cookiestore.delete([{name: 'a'}, {name: 'b'}, {name: 'c'}]);
```
I.e. change the signature to

```webidl
   Promise<void> delete(optional (CookieStoreSetOptions or sequence<CookieStoreSetOptions>));
```


Now you might use it in this form:
```js
const cookies = await cookieStore.getAll();
await cookieStore.delete(cookies);
```
But if that wasn't supported, you'd need to write:
```js
const cookies = await cookieStore.getAll();
await Promise.all(cookies.map(cookie => cookiestore.delete(cookie));
```
... which is where the Promise-fu comes in.

**Comment by dfabulich** [comment]
My understanding is that the TC39 language-level decision is "Promise.all is good enough; specific APIs can/should add sugar if they want to make it easier to perform bulk promise-returning operations." Is that your understanding as well?

But then, if you're going to say "you can't add sugar at the API level, either," then there's nowhere at all to add sugar.

**Comment by pwnall** [comment]
I generally agree with @domenic unless @dfabulich or someone else has a use case where the performance benefits justify the extra complexity of a special case.

Asides from the general API design principles covered by @domenic, having any form of multiple writes in the API means we'd have to consider atomicity guarantees. If we offered atomicity guarantees, that'd require new backend capabilities, at least in Chrome. If we didn't offer atomicity guarantees, this would be a very rough edge in the API.

On the benefits side, I'm guessing we'd get better latency by being able to batch multiple delete requests in a single IPC. I currently don't think this benefit outweighs all the extra complexity I've described above. However, I'm willing to reconsider if given a strong use case. If anyone here has that use case, please comment below, and I'll reopen the issue.
