### ISSUE TITLE
CookieStoreDeleteOptions - why do we have secure/sameSite ?

### ISSUE THREAD

**Issue by inexorabletash** [WICG/cookie-store#77]
Since only name/domain/path are used for updating (and thus deleting) cookies per https://tools.ietf.org/html/rfc6265#section-5.3, why do we need the secure/sameSite options for the `delete()` method? 

Technically these are valid input into the _When the user agent "receives a cookie"..._ algorithm, but they don't change behavior in the removal case.

If I'm wrong, we should document what the utility is.

**Comment by pwnall** [comment]
I don't think we need the options.

The main reason for how things are is that at the time I wrote the IDL I didn't know if passing unknown properties in a dictionary results in an exception or not. I would really like to support passing results from `get()` / `getAll()` straight into `delete()`.

**Comment by inexorabletash** [comment]
Cool. I'll remove them, maybe in #81
