### ISSUE TITLE
bikeshed errors should tell Travis that the build failed

### ISSUE THREAD

**Issue by rtoy** [WICG/cookie-store#85]
Look at https://travis-ci.org/WICG/cookie-store/builds/409965529. There are bikeshed errors which should have stopped the build, but Travis continues and checks in the new html version.  In some ways, this is ok, but we should be notified about bikeshed producing errors.

**Comment by rtoy** [comment]
Actually, bikeshed returns an exit code of 0, so bikeshed thinks it successfully generated the output.  Not sure that's what we want because linking errors will go unnoticed.

**Comment by inexorabletash** [comment]
We'd probably need a new bikeshed argument to make it fail on warnings?

**Comment by rtoy** [comment]
That would be cool.  We could just grab the output and grep for ERROR, but a command-line option would be nice.
