### ISSUE TITLE
spec should handle service worker lifetime issues

### ISSUE THREAD

**Issue by wanderview** [WICG/cookie-store#88]
The cookie store spec is currently a bit vague about what happens when a cookiechange event fires in a service worker context.  It seems to imply that the SW will be started in that case, but does not explicitly spec this.  Any events fired that start the SW should also extend ExtendableEvent so that the handler can keep the worker alive with waitUntil().

This is probably largely solvable by using:

https://w3c.github.io/ServiceWorker/#fire-functional-event-algorithm

And extending for events fired at the SW:

https://w3c.github.io/ServiceWorker/#extendableevent-interface

A bit awkward that these should not have the waitUntil in other contexts, though.

**Comment by inexorabletash** [comment]
Yeah, blink impl has `ExtendableCookieChangeEvent`, that needs to be reflected in the spec.

**Comment by inexorabletash** [comment]
The spec also doesn't talk about filtering changes according to subscriptions
