### ISSUE TITLE
Subscriptions are per registration, but are set from install event

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/cookie-store#92]
This seems a bit weird. Limiting to the install event seems like is meant to prevent old versions of a SW from getting events only the new version cares about, but because subscriptions are stored on the registration (as opposed to the actual worker), the old version will still get events the new version subscribed for, until that new version becomes the active version.

Perhaps two possible more sensible ways would to either:

1. Change subscription to be on ServiceWorkerRegistration, like push API (and allow changes at any time). That at least makes it clear that it is a per registration thing.

2. Or change subscriptions to be per service worker version rather than registration, and perhaps change the API to be exposed on InstallEvent rather than the cookie store object?

**Comment by jakearchibald** [comment]
Thoughts on 1:

* https://w3c.github.io/ServiceWorker/#navigationpreloadmanager is a good model to follow.
* You'd have to provide a way to unsubscribe.
* Developers would need to remember to unsubscribe properly. The gotcha is v1 of the service worker might subscribe, v2 would unsubscribe, v3 would do neither. But if the user never uses v2 they remain subscribed.
* This allows subscription from a page. You could also modify the subscriptions of many service worker registrations from one piece of code.

Thoughts on 2:

* I don't think we use this pattern currently. We thought about it for navigation preload until we required changing the header throughout the life of the service worker. The pattern we looked at was extending the `InstallEvent` to add the API.
* If a new service worker doesn't care about the subscription anymore, then it just omits the subscription call. This is kinda nice for cleanup, and reduces the chance of an unused subscription.
* You need to ship a new service worker to change subscriptions.
* This pattern is useful if bad things can happen if the service worker script isn't prepared for the feature. But I don't think that's the case here.

I'm leaning towards 1.

**Comment by inexorabletash** [comment]
https://github.com/WICG/cookie-store/pull/116 should cover this on the spec side

**Comment by ayuishii** [comment]
Thanks for the discussion!
Closing this issue and addressing followup spec changes on https://github.com/WICG/cookie-store/issues/180
