### ISSUE TITLE
Remove set(CookieStoreSetExtraOptions options)?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/cookie-store#93]
This creates a situation where we have an options object with required options.

Sure, it means the output of `get` can be passed to `set` (after modifications), but this is racey, and not something we should encourage.

You can reduce some of the racing with web locks, but since responses can also set cookies, it isn't a total solution.

**Comment by jakearchibald** [comment]
`delete(CookieStoreDeleteOptions options)` has the same problem. Options shouldn't be required.

**Comment by domenic** [comment]
It seems like the current draft still keeps this options API. Should this be closed? If so, it'd be good to at least explain the potential race and danger.

**Comment by ayuishii** [comment]
Sounds good, will look into expanding this [section](https://github.com/WICG/cookie-store/blob/main/explainer.md#subtleties) in the explainer to talk about the dangers.
