### ISSUE TITLE
Migration to WebApps WG: Implementor interest?

### ISSUE THREAD

**Issue by LJWatson** [WICG/cookie-store#96]
This specification has been proposed for migration to the [WebApps WG](https://w3c.github.io/charter-drafts/webapps-2019) (which is expected to partly replace the WebPlat WG). For this to happen, we need expressions of interest/intent to commit from at least two implementors.

Please let us know if you plan to implement this specification, or if you can point to any publicly documented expressions of interest from implementors.

The draft WebApps charter will go to the Advisory Committee (AC) within the next two or three weeks, so quick responses may make the difference.

@Chaals @marcoscaceres

**Comment by marcoscaceres** [comment]
Speaking to Mozilla folks, **we don't currently have any plans to implement this specification**. 

However, we are supportive of it moving to the Web Apps WG and are happy to provide feedback during the standardization process. 

As there is intent to implement on the Blink side, I'll close this and mark it for inclusion in the WebApps WG Charter (though let us know if you prefer for some other group to take it?). 

Once the Web Apps WG is set up, I can help with migrating the spec over to the WebApps WG.
