### ISSUE TITLE
Introduction: Broken link to Montulli article

### ISSUE THREAD

**Issue by js-choi** [WICG/cookie-store#97]
The phrase “valuable state-management mechanism” links to an article by [Lou Montulli](https://en.m.wikipedia.org/wiki/Lou_Montulli) originally on montulli-blog.com, but this domain has lapsed and been squatted. The [article is still available online on Blogger](http://montulli.blogspot.com/2013/05/the-reasoning-behind-web-cookies.html?m=1).

**Comment by inexorabletash** [comment]
Thanks!
